
on: [ pull_request, push ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v4
    - uses: efcs/action/get-email@main
      id: get-email
    - run: echo ${{ steps.get-email.outputs.user-email }}

