
on: [ pull_request  ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ rizzo-runner-1-set ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: foobar
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT | jq
    - run: git log --pretty=format:%ae | awk '/<pattern>/ && !line{line=$0} END{print line}'
    - name: Get PR Author Email Address
      run: sudo docker ps
    - run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: $GITHUB_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/users/${{ github.actor }}
    - run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: $GITHUB_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        ${{ github.event.pull_request._links.commits.href }}
    - run: ls -lart && pwd && ls -lart ../ && ls -lart ../../
    - run: git status
    - run: python3 ./get-email/main.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PULL_REQUEST_COMMITS_HREF: ${{ github.event.pull_request._links.commits.href }}
  run-on-success:
    # Check if the PR has label libcxx-stage3-tests
    if: contains(github.event.pull_request.labels.*.name, 'libcxx-stage3-tests')
    needs: [ run ]
    runs-on: [ rizzo-runner-1-set ]
    steps:
      - run: |
          echo "The name of the pusher: ${{ github.event.pusher.name }}"
    

