
on: [ pull_request ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: false
    - name: foobar
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT | jq
    - run: git log --pretty=format:%ae | awk '/<pattern>/ && !line{line=$0} END{print line}'
    - name: Get PR Author Email Address
      run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"
    - run: |-
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/users/${{ github.actor }}
