
on: [ pull_request, push ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v4
      with:
        depth: 100
    - name: foobar
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT | jq
    - run: git log --pretty=format:%ae | awk '/<pattern>/ && !line{line=$0} END{print line}'
    - name: Get PR Author Email Address
      run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"
