
on: [ pull_request ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: efcs/action/reject-user@main
      id: get-email
    - run: echo ${{ steps.get-email.outputs.user-email }}

