name: "Labelling new pull requests"

permissions:
  contents: read

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
      - name: foobar
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT | jq
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: libcxx-stage3-tests

