
on: [ push ]

permissions:
  checks: write
  statuses: write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: efcs/action/python-test@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        test_results: ./python-test/results.json
