
on: [ push ]

permissions:
  checks: read|write
  statuses: read|write

jobs:
  run:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: efcs/action/python-test@main
